version: '2'
services:
  jhipstersampleapplication321-app:
    image: jhipstersampleapplication321
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapplication321-postgresql:5432/jhipsterSampleApplication321
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  jhipstersampleapplication321-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstersampleapplication321-postgresql
